//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrokeParserConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrokeParserConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add device 1: /dev/input/event11        ///
        ///  name:     &quot;rt5648-audio Intel MID Audio Jack&quot;        ///
        ///add device 2: /dev/input/event10        ///
        ///  name:     &quot;headset_dev&quot;        ///
        ///add device 3: /dev/input/event9        ///
        ///  name:     &quot;headset_dev&quot;        ///
        ///add device 4: /dev/input/event8        ///
        ///  name:     &quot;headset_dev&quot;        ///
        ///add device 5: /dev/input/event7        ///
        ///  name:     &quot;headset_dev&quot;        ///
        ///add device 6: /dev/input/event6        ///
        ///  name:     &quot;headset_dev&quot;        ///
        ///add device 7: /dev/input/event2        ///
        ///  name:     &quot;mid_powerbtn&quot;        ///
        ///add device 8: /dev/input/event1        ///
        ///  name:     &quot;gpio-k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrokesLog1 {
            get {
                return ResourceManager.GetString("StrokesLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add device 1: /dev/input/event11
        ///
        ///  name:     &quot;rt5648-audio Intel MID Audio Jack&quot;
        ///
        ///add device 2: /dev/input/event10
        ///
        ///  name:     &quot;headset_dev&quot;
        ///
        ///add device 3: /dev/input/event9
        ///
        ///  name:     &quot;headset_dev&quot;
        ///
        ///add device 4: /dev/input/event8
        ///
        ///  name:     &quot;headset_dev&quot;
        ///
        ///add device 5: /dev/input/event7
        ///
        ///  name:     &quot;headset_dev&quot;
        ///
        ///add device 6: /dev/input/event6
        ///
        ///  name:     &quot;headset_dev&quot;
        ///
        ///add device 7: /dev/input/event2
        ///
        ///  name:     &quot;mid_powerbtn&quot;
        ///
        ///add device 8: /dev/input/event1
        ///
        ///  na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string teste {
            get {
                return ResourceManager.GetString("teste", resourceCulture);
            }
        }
    }
}
