//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace decision_tree.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("decision_tree.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1,3.5,1.4,0.2,I. setosa
        ///4.9,3.0,1.4,0.2,I. setosa
        ///4.7,3.2,1.3,0.2,I. setosa
        ///4.6,3.1,1.5,0.2,I. setosa
        ///5.0,3.6,1.4,0.2,I. setosa
        ///5.4,3.9,1.7,0.4,I. setosa
        ///4.6,3.4,1.4,0.3,I. setosa
        ///5.0,3.4,1.5,0.2,I. setosa
        ///4.4,2.9,1.4,0.2,I. setosa
        ///4.9,3.1,1.5,0.1,I. setosa
        ///5.4,3.7,1.5,0.2,I. setosa
        ///4.8,3.4,1.6,0.2,I. setosa
        ///4.8,3.0,1.4,0.1,I. setosa
        ///4.3,3.0,1.1,0.1,I. setosa
        ///5.8,4.0,1.2,0.2,I. setosa
        ///5.7,4.4,1.5,0.4,I. setosa
        ///5.4,3.9,1.3,0.4,I. setosa
        ///5.1,3.5,1.4,0.3,I. setosa
        ///5.7,3.8,1.7,0.3,I. setosa        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flowers {
            get {
                return ResourceManager.GetString("flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tchStrt,tchEnd,duration,dist2prev,xMean,yMean,MMean,xMax,yMax,MMax,xMin,yMin,MMin,relocationX,relocationY,distanceX,distanceY,distance,averagespeedx,averagespeedy,averagespeed,averageAccelerationX,averageAccelerationY,averageAcceleration,avrAngVX,avrAngVY,averageAngularAccelerationx,averageAngularAccelerationY,dist2start,wj1,wj2,angleM,STKW,Emotion,Valence,Arousal
        ///27775.1822,27775.26837,0.086174,0,930.625,1693.375,57,1037,1961,57,822,1471,1471,215,490,215,490,535.0934498,2494.952074,5686.169842,6234.834284 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strokes {
            get {
                return ResourceManager.GetString("strokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tchStrt;tchEnd;duration;dist2prev;xMean;yMean;MMean;xMax;yMax;MMax;xMin;yMin;MMin;relocationX;relocationY;distanceX;distanceY;distance;averagespeedx;averagespeedy;averagespeed;averageAccelerationX;averageAccelerationY;averageAcceleration;avrAngVX;avrAngVY;averageAngularAccelerationx;averageAngularAccelerationY;dist2start;wj1;wj2;angleM;STKW;Emotion;Valence;Arousal
        ///27775,1822000;27775,2683700;0,0861740;0,0000000;930,6250000;1693,3750000;57,0000000;1037,0000000;1961,0000000;57,0000000;822,0000000;1471,000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strokes3 {
            get {
                return ResourceManager.GetString("strokes3", resourceCulture);
            }
        }
    }
}
